In [117]:
! pip install feature_engine==1.8.0 --quiet

In [118]:
!pip install optuna==4.8.0 -q

In [349]:
!pip uninstall scikit-learn -y
!pip install scikit-learn==1.5.2

Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Would remove:
    /usr/local/lib/python3.12/dist-packages/scikit_learn-1.5.2.dist-info/*
    /usr/local/lib/python3.12/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.12/dist-packages/sklearn/*
Proceed (Y/n)? ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/uninstall.py", line 106, in run
    uninstall_pathset = req.uninstall(
                        ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/req/req_install.py", line 722, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/req/req_uninstall.py", line 364, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/req/req_uninstall.py", line 404, in _allowed_to_proceed
    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/misc.py", line 235, in ask
    response = input(message)
               ^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1673, in print
    with self:
         ^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 865, in __exit__
    self._exit_buffer()
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 2060, in _check_buffer
    self.file.write(text)
KeyboardInterrupt
^C
Requirement already satisfied: scikit-learn==1.5.2 in /usr/local/lib/python3.12/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)

In [350]:
import pandas as pd
import numpy as np
import sys
import os
import gc

import unicodedata
import re

import seaborn as sns
import matplotlib.pyplot as plt

import feature_engine
from feature_engine.selection import (
    RecursiveFeatureElimination,
    DropConstantFeatures,
    DropDuplicateFeatures,
)
import optuna

from sklearn.pipeline import Pipeline
from sklearn.base import clone
from sklearn.model_selection import TimeSeriesSplit, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score, make_scorer
from sklearn.preprocessing import StandardScaler
import sklearn

import xgboost
import lightgbm
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

import time

print(f"Versão:")
print(f'Python: {sys.version}')
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')
print("Feature Engine:", feature_engine.__version__)
print("Scikit Learn:", sklearn.__version__)
print("Optuna:", optuna.__version__)
print("XGBoost:", xgboost.__version__)
print("LightGBM:", lightgbm.__version__)

Versão:
Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Pandas: 2.2.2
Numpy: 2.0.2
Feature Engine: 1.8.0
Scikit Learn: 1.6.1
Optuna: 4.8.0
XGBoost: 3.2.0
LightGBM: 4.6.0

In [175]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
path_main = '/content/drive/MyDrive/ML-UFF'

Mounted at /content/drive

In [176]:
def get_data_frame(path_dataset: str):
  data = pd.read_csv(path_dataset)
  return data

In [233]:
path = f'{path_main}/df_agg.csv'
df = get_data_frame(path)

In [234]:
df.rename(columns={'classificacao': 'total_casos','Data':'data'}, inplace=True)

In [235]:
df['data'] = pd.to_datetime(df['data'])
df.set_index('data', inplace=True)

In [236]:
df.shape, df.columns

((92794, 44),
 Index(['cs_sexo', 'cs_gestant', 'febre', 'mialgia', 'cefaleia', 'exantema',
        'vomito', 'nausea', 'dor_retro', 'artralgia', 'artrite', 'conjuntvit',
        'petequia_n', 'laco', 'diabetes', 'hipertensa', 'renal', 'hematolog',
        'hepatopat', 'classi_fin', 'evolucao', 'idade', 'faixa_etaria', 'year',
        'month', 'day_week', 'day_month', 'day_month_start', 'day_month_end',
        'day_quarter_start', 'day_quarter_end', 'day_year_start',
        'day_year_end', 'total_casos', 'desfecho', 'chuva_dia',
        'temp_media_dia', 'temp_max_dia', 'temp_min_dia', 'umidade_dia',
        'vento_velocidade_horaria_m_s', 'score_gravidade', 'calor_extremo',
        'faixa_umidade'],
       dtype='object'))

In [237]:
def print_nan(df):
    nan_count = df.isna().sum()
    # Filtra apenas onde a contagem é maior que zero
    nan_only = nan_count[nan_count > 0].sort_values(ascending=False)

    if nan_only.empty:
        print("Nenhum valor NaN encontrado!")
    else:
        print("Colunas com valores NaN:")
        print(nan_only)

In [238]:
print_nan(df)

Colunas com valores NaN:
chuva_dia                       177
temp_media_dia                  177
temp_max_dia                    177
temp_min_dia                    177
umidade_dia                     177
vento_velocidade_horaria_m_s    177
faixa_umidade                   177
dtype: int64

In [239]:
df.index

DatetimeIndex(['2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
               '2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
               '2020-01-01', '2020-01-01',
               ...
               '2026-04-21', '2026-04-21', '2026-04-21', '2026-04-21',
               '2026-04-22', '2026-04-22', '2026-04-22', '2026-04-22',
               '2026-04-22', '2026-04-23'],
              dtype='datetime64[ns]', name='data', length=92794, freq=None)

### Train Test Split

In [240]:
def train_test_split_by_date(
    data: pd.DataFrame | pd.Series,
    start_date: str,
    split_date: str,
    end_date: str | None = None,
):
    if not isinstance(data.index, pd.DatetimeIndex):
        raise ValueError("data must have a DatetimeIndex")

    # garantir ordem temporal
    data = data.sort_index()

    start_date = pd.to_datetime(start_date)
    split_date = pd.to_datetime(split_date)
    end_date = pd.to_datetime(end_date) if end_date else data.index.max()

    if not (start_date < split_date < end_date):
        raise ValueError("start_date < split_date < end_date is required")

    # 🔑 slicing robusto (não depende da data existir no índice)
    start_pos = data.index.searchsorted(start_date, side="left")
    end_pos = data.index.searchsorted(end_date, side="right")

    data = data.iloc[start_pos:end_pos]

    split_pos = data.index.searchsorted(split_date, side="right")
    train = data.iloc[:split_pos]
    test = data.iloc[split_pos:]

    return train, test

In [241]:
lags = [7, 15, 21, 30, 45, 50, 60]
n_nans = lags[-1]
n_nans

60

In [242]:

start_date = df.index.min().strftime('%Y-%m-%d')
split_date_test = '2025-12-24' # 60 dias maior lag gerado
split_date_validation = '2025-08-26' # 60 dias
end_date = df.index.max().strftime('%Y-%m-%d')

start_date, split_date_validation, split_date_test, end_date

('2020-01-01', '2025-08-26', '2025-12-24', '2026-04-23')

In [243]:
df_train, df_test = train_test_split_by_date(df, start_date, split_date_test)

In [244]:
len(df_test.index.unique())

119

In [245]:
df_test.index.unique()

DatetimeIndex(['2025-12-25', '2025-12-26', '2025-12-27', '2025-12-28',
               '2025-12-29', '2025-12-30', '2025-12-31', '2026-01-01',
               '2026-01-02', '2026-01-03',
               ...
               '2026-04-14', '2026-04-15', '2026-04-16', '2026-04-17',
               '2026-04-18', '2026-04-19', '2026-04-20', '2026-04-21',
               '2026-04-22', '2026-04-23'],
              dtype='datetime64[ns]', name='data', length=119, freq=None)

In [246]:
df_train.index, df_test.index

(DatetimeIndex(['2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
                '2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
                '2020-01-01', '2020-01-01',
                ...
                '2025-12-23', '2025-12-24', '2025-12-24', '2025-12-24',
                '2025-12-24', '2025-12-24', '2025-12-24', '2025-12-24',
                '2025-12-24', '2025-12-24'],
               dtype='datetime64[ns]', name='data', length=91528, freq=None),
 DatetimeIndex(['2025-12-25', '2025-12-25', '2025-12-25', '2025-12-25',
                '2025-12-25', '2025-12-26', '2025-12-26', '2025-12-26',
                '2025-12-26', '2025-12-26',
                ...
                '2026-04-21', '2026-04-21', '2026-04-21', '2026-04-21',
                '2026-04-22', '2026-04-22', '2026-04-22', '2026-04-22',
                '2026-04-22', '2026-04-23'],
               dtype='datetime64[ns]', name='data', length=1266, freq=None))

In [247]:
df_train, df_val = train_test_split_by_date(df_train, start_date, split_date_validation)

In [248]:
len(df_val.index.unique())

120

In [249]:
df_train.index, df_val.index

(DatetimeIndex(['2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
                '2020-01-01', '2020-01-01', '2020-01-01', '2020-01-01',
                '2020-01-01', '2020-01-01',
                ...
                '2025-08-25', '2025-08-25', '2025-08-25', '2025-08-25',
                '2025-08-25', '2025-08-25', '2025-08-26', '2025-08-26',
                '2025-08-26', '2025-08-26'],
               dtype='datetime64[ns]', name='data', length=90644, freq=None),
 DatetimeIndex(['2025-08-27', '2025-08-27', '2025-08-27', '2025-08-27',
                '2025-08-27', '2025-08-27', '2025-08-27', '2025-08-27',
                '2025-08-27', '2025-08-27',
                ...
                '2025-12-23', '2025-12-24', '2025-12-24', '2025-12-24',
                '2025-12-24', '2025-12-24', '2025-12-24', '2025-12-24',
                '2025-12-24', '2025-12-24'],
               dtype='datetime64[ns]', name='data', length=884, freq=None))

# Features Train/Validation/Test Split

#### Recriando para que não haja vazamento de dados

In [250]:
column_target = 'total_casos'

In [251]:
def fourier_features(df, columns, periods, n_terms_list):
    t = np.arange(len(df))

    for col in columns:
        for period, n_terms in zip(periods, n_terms_list):
            period = int(period)  # ← garante que não vira array/lista

            for k in range(1, n_terms + 1):
                df[f"{col}_fourier_cos_p{period}_k{k}"] = np.cos(2 * np.pi * k * t / period)
                df[f"{col}_fourier_sin_p{period}_k{k}"] = np.sin(2 * np.pi * k * t / period)

    return df


seasonal_periods = [7, 30.44, 365.25]  # Semanal, Mensal e Anual
n_terms_list = [3, 1, 2] # Complexidade de cada onda


df_train = fourier_features(df_train, ['ciclos'], seasonal_periods, n_terms_list)
df_val = fourier_features(df_val, ['ciclos'], seasonal_periods, n_terms_list)
df_test = fourier_features(df_test, ['ciclos'], seasonal_periods, n_terms_list)


print_nan(df_train)
print_nan(df_val)
print_nan(df_test)


print(df_train.shape)
print(df_val.shape)
df_test.shape

Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!
Colunas com valores NaN:
chuva_dia                       177
temp_media_dia                  177
temp_max_dia                    177
temp_min_dia                    177
umidade_dia                     177
vento_velocidade_horaria_m_s    177
faixa_umidade                   177
dtype: int64
(90644, 56)
(884, 56)

(1266, 56)

In [252]:
# Lista de sintomas/sinais para o score (ajuste se necessário)
def sinais_gravidade(df):
  sinais_gravidade = [
      'petequia_n', 'laco', 'renal', 'hematolog', 'hepatopat', 'vomito'
  ]

  # Criando a coluna: ela soma quantos desses sinais cada paciente apresenta
  # Se o paciente tem 1 em todos, o score é 6. Se não tem nenhum, é 0.
  df['score_gravidade'] = df[sinais_gravidade].sum(axis=1)
  return df

In [253]:
df_train = sinais_gravidade(df_train)
df_val = sinais_gravidade(df_val)
df_test = sinais_gravidade(df_test)

In [254]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(90644, 56)
(884, 56)

(1266, 56)

In [255]:
# Agregação Diária: Transformando pacientes em contagens e médias
def agg_diaria(X):
  X = X.groupby('data').agg({
      'total_casos': 'count',
      'score_gravidade': 'mean',     # Gravidade média dos casos do dia
      'idade': 'mean',               # Idade média dos infectados
      'chuva_dia': 'first',          # Já está agregado, pegamos o valor do dia
      'temp_max_dia': 'first',
      'temp_min_dia': 'first',
      'umidade_dia': 'first',
      'year': 'first',
      'month': 'first',
      'day_week': 'first'
  })


  X['score_gravidade'] = X['score_gravidade'].ffill().bfill()
  X['idade'] = X['idade'].ffill().bfill()

  # Para o clima, preenchemos pequenas falhas com interpolação
  X[['chuva_dia', 'temp_min_dia', 'temp_max_dia', 'umidade_dia']] = X[['chuva_dia', 'temp_min_dia', 'temp_max_dia', 'umidade_dia']].interpolate()
  return X

In [256]:
df_train = agg_diaria(df_train)
df_val = agg_diaria(df_val)
df_test = agg_diaria(df_test)

In [257]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1893, 10)
(120, 10)

(119, 10)

In [258]:
df_train[column_target]

data
2020-01-01    11
2020-01-02    18
2020-01-03    19
2020-01-04     5
2020-01-05     9
              ..
2025-08-22     9
2025-08-23    12
2025-08-24     9
2025-08-25     7
2025-08-26     4
Name: total_casos, Length: 1893, dtype: int64

In [259]:
def acum_lags(X, lags = [7, 15, 21, 30, 45, 50, 60]):
  for lag in lags:
      # Chuva acumulada nos últimos X dias (Soma móvel)
      X[f'chuva_acum_{lag}d'] = X['chuva_dia'].rolling(window=lag).sum()
      X['faixa_chuva'] = pd.qcut(X[f'chuva_acum_{lag}d'], q=4, labels=['Baixa', 'Média', 'Alta', 'Muito Alta'])

      # Temperatura média defasada (O que aconteceu há X dias)
      X[f'temp_max_lag_{lag}d'] = X['temp_max_dia'].shift(lag)
      X[f'temp_min_lag_{lag}d'] = X['temp_min_dia'].shift(lag)

      # Gravidade defasada (Para ver se a gravidade sobe antes dos casos)
      X[f'gravidade_lag_{lag}d'] = X['score_gravidade'].shift(lag)

      # Cálculo de Médias Móveis (Suavização da curva de casos)
      X[f'casos_mm{lag}d'] = X['total_casos'].rolling(window=lag).mean()

  return X

In [260]:
df_train = acum_lags(df_train, lags)
df_val = acum_lags(df_val, lags)
df_test = acum_lags(df_test, lags)

In [261]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1893, 46)
(120, 46)

(119, 46)

In [262]:
def index_transform(df):
  # Transformando a coluna de dados:
  df['year'] = df.index.year
  df['month'] = df.index.month
  df['day_week'] = df.index.day_of_week
  df['day_month'] = df.index.day
  df['day_month_start'] = df.index.is_month_start.astype(int)
  df['day_month_end'] = df.index.is_month_end.astype(int)
  df['day_quarter_start'] = df.index.is_quarter_start.astype(int)
  df['day_quarter_end'] = df.index.is_quarter_end.astype(int)
  df['day_year_start'] = df.index.is_year_start.astype(int)
  df['day_year_end'] = df.index.is_year_end.astype(int)

  return df

In [263]:
df_train = index_transform(df_train)
df_val = index_transform(df_val)
df_test = index_transform(df_test)

In [264]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1893, 53)
(120, 53)

(119, 53)

In [265]:
def interpolation(df):
  cols_clima = ['temp_max_dia', 'temp_min_dia', 'umidade_dia', 'chuva_dia']
  df[cols_clima] = df[cols_clima].interpolate(method='linear', limit_direction='both')
  return df

In [266]:
df_train = interpolation(df_train)
df_val = interpolation(df_val)
df_test = interpolation(df_test)

In [267]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1893, 53)
(120, 53)

(119, 53)

In [268]:
df_train.columns

Index(['total_casos', 'score_gravidade', 'idade', 'chuva_dia', 'temp_max_dia',
       'temp_min_dia', 'umidade_dia', 'year', 'month', 'day_week',
       'chuva_acum_7d', 'faixa_chuva', 'temp_max_lag_7d', 'temp_min_lag_7d',
       'gravidade_lag_7d', 'casos_mm7d', 'chuva_acum_15d', 'temp_max_lag_15d',
       'temp_min_lag_15d', 'gravidade_lag_15d', 'casos_mm15d',
       'chuva_acum_21d', 'temp_max_lag_21d', 'temp_min_lag_21d',
       'gravidade_lag_21d', 'casos_mm21d', 'chuva_acum_30d',
       'temp_max_lag_30d', 'temp_min_lag_30d', 'gravidade_lag_30d',
       'casos_mm30d', 'chuva_acum_45d', 'temp_max_lag_45d', 'temp_min_lag_45d',
       'gravidade_lag_45d', 'casos_mm45d', 'chuva_acum_50d',
       'temp_max_lag_50d', 'temp_min_lag_50d', 'gravidade_lag_50d',
       'casos_mm50d', 'chuva_acum_60d', 'temp_max_lag_60d', 'temp_min_lag_60d',
       'gravidade_lag_60d', 'casos_mm60d', 'day_month', 'day_month_start',
       'day_month_end', 'day_quarter_start', 'day_quarter_end',
       'day_year_start', 'day_year_end'],
      dtype='object')

In [269]:
print_nan(df_train)
print_nan(df_val)
print_nan(df_test)

Colunas com valores NaN:
temp_min_lag_60d     60
gravidade_lag_60d    60
temp_max_lag_60d     60
faixa_chuva          59
casos_mm60d          59
chuva_acum_60d       59
temp_max_lag_50d     50
gravidade_lag_50d    50
temp_min_lag_50d     50
casos_mm50d          49
chuva_acum_50d       49
temp_min_lag_45d     45
gravidade_lag_45d    45
temp_max_lag_45d     45
casos_mm45d          44
chuva_acum_45d       44
temp_max_lag_30d     30
temp_min_lag_30d     30
gravidade_lag_30d    30
chuva_acum_30d       29
casos_mm30d          29
temp_max_lag_21d     21
gravidade_lag_21d    21
temp_min_lag_21d     21
casos_mm21d          20
chuva_acum_21d       20
gravidade_lag_15d    15
temp_min_lag_15d     15
temp_max_lag_15d     15
chuva_acum_15d       14
casos_mm15d          14
temp_max_lag_7d       7
gravidade_lag_7d      7
temp_min_lag_7d       7
chuva_acum_7d         6
casos_mm7d            6
dtype: int64
Colunas com valores NaN:
temp_min_lag_60d     60
gravidade_lag_60d    60
temp_max_lag_60d     60
faixa_chuva          59
casos_mm60d          59
chuva_acum_60d       59
temp_max_lag_50d     50
gravidade_lag_50d    50
temp_min_lag_50d     50
casos_mm50d          49
chuva_acum_50d       49
temp_min_lag_45d     45
gravidade_lag_45d    45
temp_max_lag_45d     45
casos_mm45d          44
chuva_acum_45d       44
temp_max_lag_30d     30
temp_min_lag_30d     30
gravidade_lag_30d    30
chuva_acum_30d       29
casos_mm30d          29
temp_max_lag_21d     21
gravidade_lag_21d    21
temp_min_lag_21d     21
casos_mm21d          20
chuva_acum_21d       20
gravidade_lag_15d    15
temp_min_lag_15d     15
temp_max_lag_15d     15
chuva_acum_15d       14
casos_mm15d          14
temp_max_lag_7d       7
gravidade_lag_7d      7
temp_min_lag_7d       7
chuva_acum_7d         6
casos_mm7d            6
dtype: int64
Colunas com valores NaN:
temp_min_lag_60d     60
gravidade_lag_60d    60
temp_max_lag_60d     60
faixa_chuva          59
casos_mm60d          59
chuva_acum_60d       59
temp_max_lag_50d     50
gravidade_lag_50d    50
temp_min_lag_50d     50
casos_mm50d          49
chuva_acum_50d       49
temp_min_lag_45d     45
gravidade_lag_45d    45
temp_max_lag_45d     45
casos_mm45d          44
chuva_acum_45d       44
temp_max_lag_30d     30
temp_min_lag_30d     30
gravidade_lag_30d    30
chuva_acum_30d       29
casos_mm30d          29
temp_max_lag_21d     21
gravidade_lag_21d    21
temp_min_lag_21d     21
casos_mm21d          20
chuva_acum_21d       20
gravidade_lag_15d    15
temp_min_lag_15d     15
temp_max_lag_15d     15
chuva_acum_15d       14
casos_mm15d          14
temp_max_lag_7d       7
gravidade_lag_7d      7
temp_min_lag_7d       7
chuva_acum_7d         6
casos_mm7d            6
dtype: int64

In [270]:
# Criando faixas de umidade
def faixa_umidade(df):
  df['faixa_umidade'] = pd.cut(df['umidade_dia'], bins=[0, 40, 60, 80, 100],
                                      labels=['Muito Seco', 'Seco', 'Ideal', 'Úmido'])
  return df

In [271]:
df_train = faixa_umidade(df_train)
df_val = faixa_umidade(df_val)
df_test = faixa_umidade(df_test)

In [272]:
n_nans # quantidade máxima de NaNs esperado no val/test lags[-1]

60

In [273]:
df_train = df_train.iloc[n_nans:]
df_val = df_val.iloc[n_nans:]
df_test = df_test.iloc[n_nans:]

In [274]:
print_nan(df_train)
print_nan(df_val)
print_nan(df_test)

Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!

In [275]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1833, 54)
(60, 54)

(59, 54)

In [276]:
def fourier_features(df, columns, periods, n_terms_list):
    t = np.arange(len(df))

    for col in columns:
        for period, n_terms in zip(periods, n_terms_list):
            period = int(period)  # ← garante que não vira array/lista

            for k in range(1, n_terms + 1):
                df[f"{col}_fourier_cos_p{period}_k{k}"] = np.cos(2 * np.pi * k * t / period)
                df[f"{col}_fourier_sin_p{period}_k{k}"] = np.sin(2 * np.pi * k * t / period)

    return df

In [277]:
seasonal_periods = [7, 30.44, 365.25]  # Semanal, Mensal e Anual
n_terms_list = [3, 1, 2] # Complexidade de cada onda

In [278]:
df_train = fourier_features(df_train, ['ciclos'], seasonal_periods, n_terms_list)
df_val = fourier_features(df_val, ['ciclos'], seasonal_periods, n_terms_list)
df_test = fourier_features(df_test, ['ciclos'], seasonal_periods, n_terms_list)

In [279]:
print_nan(df_train)
print_nan(df_val)
print_nan(df_test)

Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!

In [280]:
print(df_train.shape)
print(df_val.shape)
df_test.shape

(1833, 66)
(60, 66)

(59, 66)

In [286]:
df_train.columns

Index(['total_casos', 'score_gravidade', 'idade', 'chuva_dia', 'temp_max_dia',
       'temp_min_dia', 'umidade_dia', 'year', 'month', 'day_week',
       'chuva_acum_7d', 'faixa_chuva', 'temp_max_lag_7d', 'temp_min_lag_7d',
       'gravidade_lag_7d', 'casos_mm7d', 'chuva_acum_15d', 'temp_max_lag_15d',
       'temp_min_lag_15d', 'gravidade_lag_15d', 'casos_mm15d',
       'chuva_acum_21d', 'temp_max_lag_21d', 'temp_min_lag_21d',
       'gravidade_lag_21d', 'casos_mm21d', 'chuva_acum_30d',
       'temp_max_lag_30d', 'temp_min_lag_30d', 'gravidade_lag_30d',
       'casos_mm30d', 'chuva_acum_45d', 'temp_max_lag_45d', 'temp_min_lag_45d',
       'gravidade_lag_45d', 'casos_mm45d', 'chuva_acum_50d',
       'temp_max_lag_50d', 'temp_min_lag_50d', 'gravidade_lag_50d',
       'casos_mm50d', 'chuva_acum_60d', 'temp_max_lag_60d', 'temp_min_lag_60d',
       'gravidade_lag_60d', 'casos_mm60d', 'day_month', 'day_month_start',
       'day_month_end', 'day_quarter_start', 'day_quarter_end',
       'day_year_start', 'day_year_end', 'faixa_umidade',
       'ciclos_fourier_cos_p7_k1', 'ciclos_fourier_sin_p7_k1',
       'ciclos_fourier_cos_p7_k2', 'ciclos_fourier_sin_p7_k2',
       'ciclos_fourier_cos_p7_k3', 'ciclos_fourier_sin_p7_k3',
       'ciclos_fourier_cos_p30_k1', 'ciclos_fourier_sin_p30_k1',
       'ciclos_fourier_cos_p365_k1', 'ciclos_fourier_sin_p365_k1',
       'ciclos_fourier_cos_p365_k2', 'ciclos_fourier_sin_p365_k2'],
      dtype='object')

### Split

In [287]:
def split_target(df: pd.DataFrame, columns_target: str):
    y = df[columns_target]
    X = df.drop(columns=[columns_target])

    return X, y

In [288]:
# column_target = 'total_casos'

In [289]:
X_train, y_train = split_target(df_train, column_target)
X_val, y_val = split_target(df_val, column_target)
X_test, y_test = split_target(df_val, column_target)

In [290]:
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
X_test.shape, y_test.shape

(1833, 65) (1833,)
(60, 65) (60,)

((60, 65), (60,))

In [291]:
y_train.isna().sum().sum(), y_val.isna().sum().sum(), y_val.isna().sum().sum()

(np.int64(0), np.int64(0), np.int64(0))

# Scaler

In [294]:
X_train.columns

Index(['score_gravidade', 'idade', 'chuva_dia', 'temp_max_dia', 'temp_min_dia',
       'umidade_dia', 'year', 'month', 'day_week', 'chuva_acum_7d',
       'faixa_chuva', 'temp_max_lag_7d', 'temp_min_lag_7d', 'gravidade_lag_7d',
       'casos_mm7d', 'chuva_acum_15d', 'temp_max_lag_15d', 'temp_min_lag_15d',
       'gravidade_lag_15d', 'casos_mm15d', 'chuva_acum_21d',
       'temp_max_lag_21d', 'temp_min_lag_21d', 'gravidade_lag_21d',
       'casos_mm21d', 'chuva_acum_30d', 'temp_max_lag_30d', 'temp_min_lag_30d',
       'gravidade_lag_30d', 'casos_mm30d', 'chuva_acum_45d',
       'temp_max_lag_45d', 'temp_min_lag_45d', 'gravidade_lag_45d',
       'casos_mm45d', 'chuva_acum_50d', 'temp_max_lag_50d', 'temp_min_lag_50d',
       'gravidade_lag_50d', 'casos_mm50d', 'chuva_acum_60d',
       'temp_max_lag_60d', 'temp_min_lag_60d', 'gravidade_lag_60d',
       'casos_mm60d', 'day_month', 'day_month_start', 'day_month_end',
       'day_quarter_start', 'day_quarter_end', 'day_year_start',
       'day_year_end', 'faixa_umidade', 'ciclos_fourier_cos_p7_k1',
       'ciclos_fourier_sin_p7_k1', 'ciclos_fourier_cos_p7_k2',
       'ciclos_fourier_sin_p7_k2', 'ciclos_fourier_cos_p7_k3',
       'ciclos_fourier_sin_p7_k3', 'ciclos_fourier_cos_p30_k1',
       'ciclos_fourier_sin_p30_k1', 'ciclos_fourier_cos_p365_k1',
       'ciclos_fourier_sin_p365_k1', 'ciclos_fourier_cos_p365_k2',
       'ciclos_fourier_sin_p365_k2'],
      dtype='object')

In [298]:
fourier = X_train.filter(like='ciclo')
cols_fourier = fourier.columns.to_list()
cols_fourier

['ciclos_fourier_cos_p7_k1',
 'ciclos_fourier_sin_p7_k1',
 'ciclos_fourier_cos_p7_k2',
 'ciclos_fourier_sin_p7_k2',
 'ciclos_fourier_cos_p7_k3',
 'ciclos_fourier_sin_p7_k3',
 'ciclos_fourier_cos_p30_k1',
 'ciclos_fourier_sin_p30_k1',
 'ciclos_fourier_cos_p365_k1',
 'ciclos_fourier_sin_p365_k1',
 'ciclos_fourier_cos_p365_k2',
 'ciclos_fourier_sin_p365_k2']

In [314]:
X_train_fourier = X_train[cols_fourier]
X_val_fourier = X_val[cols_fourier]
X_test_fourier = X_test[cols_fourier]
X_test_fourier

,ciclos_fourier_cos_p7_k1,ciclos_fourier_sin_p7_k1,ciclos_fourier_cos_p7_k2,ciclos_fourier_sin_p7_k2,ciclos_fourier_cos_p7_k3,ciclos_fourier_sin_p7_k3,ciclos_fourier_cos_p30_k1,ciclos_fourier_sin_p30_k1,ciclos_fourier_cos_p365_k1,ciclos_fourier_sin_p365_k1,ciclos_fourier_cos_p365_k2,ciclos_fourier_sin_p365_k2
data,,,,,,,,,,,,
2025-10-26,1.000000,0.000000e+00,1.000000,0.000000e+00,1.000000,0.000000e+00,1.000000,0.000000e+00,1.000000,0.000000,1.000000,0.000000
2025-10-27,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,0.978148,2.079117e-01,0.999852,0.017213,0.999407,0.034422
2025-10-28,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,0.913545,4.067366e-01,0.999407,0.034422,0.997630,0.068802
2025-10-29,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,0.809017,5.877853e-01,0.998667,0.051620,0.994671,0.103102
2025-10-30,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,0.669131,7.431448e-01,0.997630,0.068802,0.990532,0.137279
2025-10-31,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,0.500000,8.660254e-01,0.996298,0.085965,0.985220,0.171293
2025-11-01,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,0.309017,9.510565e-01,0.994671,0.103102,0.978740,0.205104
2025-11-02,1.000000,-2.449294e-16,1.000000,-4.898587e-16,1.000000,-7.347881e-16,0.104528,9.945219e-01,0.992749,0.120208,0.971100,0.238673
2025-11-03,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,-0.104528,9.945219e-01,0.990532,0.137279,0.962309,0.271958
2025-11-04,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,-0.309017,9.510565e-01,0.988023,0.154309,0.952378,0.304921
2025-11-05,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,-0.500000,8.660254e-01,0.985220,0.171293,0.941317,0.337523
2025-11-06,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,-0.669131,7.431448e-01,0.982126,0.188227,0.929141,0.369725
2025-11-07,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,-0.809017,5.877853e-01,0.978740,0.205104,0.915864,0.401488
2025-11-08,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,-0.913545,4.067366e-01,0.975065,0.221922,0.901502,0.432776
2025-11-09,1.000000,-4.898587e-16,1.000000,-9.797174e-16,1.000000,-1.469576e-15,-0.978148,2.079117e-01,0.971100,0.238673,0.886071,0.463550
2025-11-10,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,-1.000000,5.665539e-16,0.966848,0.255353,0.869589,0.493776
2025-11-11,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,-0.978148,-2.079117e-01,0.962309,0.271958,0.852078,0.523416
2025-11-12,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,-0.913545,-4.067366e-01,0.957485,0.288482,0.833556,0.552435
2025-11-13,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,-0.809017,-5.877853e-01,0.952378,0.304921,0.814046,0.580800
2025-11-14,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,-0.669131,-7.431448e-01,0.946988,0.321270,0.793572,0.608477
2025-11-15,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,-0.500000,-8.660254e-01,0.941317,0.337523,0.772157,0.635432
2025-11-16,1.000000,-7.347881e-16,1.000000,-1.469576e-15,1.000000,-2.204364e-15,-0.309017,-9.510565e-01,0.935368,0.353676,0.749826,0.661635
2025-11-17,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,-0.104528,-9.945219e-01,0.929141,0.369725,0.726608,0.687053
2025-11-18,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,0.104528,-9.945219e-01,0.922640,0.385663,0.702527,0.711657
2025-11-19,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,0.309017,-9.510565e-01,0.915864,0.401488,0.677615,0.735417
2025-11-20,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,0.500000,-8.660254e-01,0.908818,0.417194,0.651899,0.758306
2025-11-21,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,0.669131,-7.431448e-01,0.901502,0.432776,0.625411,0.780296
2025-11-22,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,0.809017,-5.877853e-01,0.893919,0.448229,0.598181,0.801361
2025-11-23,1.000000,-9.797174e-16,1.000000,-1.959435e-15,1.000000,-2.939152e-15,0.913545,-4.067366e-01,0.886071,0.463550,0.570242,0.821477
2025-11-24,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,0.978148,-2.079117e-01,0.877960,0.478734,0.541628,0.840618
2025-11-25,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,1.000000,-1.133108e-15,0.869589,0.493776,0.512371,0.858764
2025-11-26,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,0.978148,2.079117e-01,0.860961,0.508671,0.482508,0.875892
2025-11-27,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,0.913545,4.067366e-01,0.852078,0.523416,0.452072,0.891981
2025-11-28,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,0.809017,5.877853e-01,0.842942,0.538005,0.421101,0.907014
2025-11-29,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,0.669131,7.431448e-01,0.833556,0.552435,0.389630,0.920971
2025-11-30,1.000000,-1.224647e-15,1.000000,-2.449294e-15,1.000000,3.431487e-15,0.500000,8.660254e-01,0.823923,0.566702,0.357698,0.933837
2025-12-01,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,0.309017,9.510565e-01,0.814046,0.580800,0.325342,0.945596
2025-12-02,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,0.104528,9.945219e-01,0.803928,0.594727,0.292600,0.956235
2025-12-03,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,-0.104528,9.945219e-01,0.793572,0.608477,0.259512,0.965740
2025-12-04,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,-0.309017,9.510565e-01,0.782980,0.622047,0.226116,0.974100
2025-12-05,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,-0.500000,8.660254e-01,0.772157,0.635432,0.192452,0.981306
2025-12-06,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,-0.669131,7.431448e-01,0.761104,0.648630,0.158559,0.987349
2025-12-07,1.000000,-1.469576e-15,1.000000,-2.939152e-15,1.000000,-4.408728e-15,-0.809017,5.877853e-01,0.749826,0.661635,0.124479,0.992222
2025-12-08,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,-0.913545,4.067366e-01,0.738326,0.674444,0.090252,0.995919
2025-12-09,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,-0.978148,2.079117e-01,0.726608,0.687053,0.055917,0.998435
2025-12-10,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,-1.000000,3.673940e-16,0.714673,0.699458,0.021516,0.999769
2025-12-11,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,-0.978148,-2.079117e-01,0.702527,0.711657,-0.012910,0.999917
2025-12-12,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,-0.913545,-4.067366e-01,0.690173,0.723644,-0.047321,0.998880
2025-12-13,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,-0.809017,-5.877853e-01,0.677615,0.735417,-0.081676,0.996659
2025-12-14,1.000000,-1.714506e-15,1.000000,-3.429011e-15,1.000000,1.961911e-15,-0.669131,-7.431448e-01,0.664855,0.746972,-0.115935,0.993257
2025-12-15,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,-0.500000,-8.660254e-01,0.651899,0.758306,-0.150055,0.988678
2025-12-16,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,-0.309017,-9.510565e-01,0.638749,0.769415,-0.183998,0.982927
2025-12-17,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,-0.104528,-9.945219e-01,0.625411,0.780296,-0.217723,0.976011
2025-12-18,-0.900969,-4.338837e-01,0.623490,7.818315e-01,-0.222521,-9.749279e-01,0.104528,-9.945219e-01,0.611886,0.790946,-0.251190,0.967938
2025-12-19,-0.222521,-9.749279e-01,-0.900969,4.338837e-01,0.623490,7.818315e-01,0.309017,-9.510565e-01,0.598181,0.801361,-0.284359,0.958718
2025-12-20,0.623490,-7.818315e-01,-0.222521,-9.749279e-01,-0.900969,-4.338837e-01,0.500000,-8.660254e-01,0.584298,0.811539,-0.317191,0.948362
2025-12-21,1.000000,-1.959435e-15,1.000000,-3.918870e-15,1.000000,-5.878305e-15,0.669131,-7.431448e-01,0.570242,0.821477,-0.349647,0.936881
2025-12-22,0.623490,7.818315e-01,-0.222521,9.749279e-01,-0.900969,4.338837e-01,0.809017,-5.877853e-01,0.556017,0.831171,-0.381689,0.924291
2025-12-23,-0.222521,9.749279e-01,-0.900969,-4.338837e-01,0.623490,-7.818315e-01,0.913545,-4.067366e-01,0.541628,0.840618,-0.413279,0.910605
2025-12-24,-0.900969,4.338837e-01,0.623490,-7.818315e-01,-0.222521,9.749279e-01,0.978148,-2.079117e-01,0.527078,0.849817,-0.444378,0.895839

In [315]:
X_train_s = X_train.drop(columns=cols_fourier)
X_val_s = X_val.drop(columns=cols_fourier)
X_test_s = X_test.drop(columns=cols_fourier)

In [316]:
X_train_s.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1833 entries, 2020-03-01 to 2025-08-26
Data columns (total 53 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   score_gravidade    1833 non-null   float64
 1   idade              1833 non-null   float64
 2   chuva_dia          1833 non-null   float64
 3   temp_max_dia       1833 non-null   float64
 4   temp_min_dia       1833 non-null   float64
 5   umidade_dia        1833 non-null   float64
 6   year               1833 non-null   int32
 7   month              1833 non-null   int32
 8   day_week           1833 non-null   int32
 9   chuva_acum_7d      1833 non-null   float64
 10  faixa_chuva        1833 non-null   category
 11  temp_max_lag_7d    1833 non-null   float64
 12  temp_min_lag_7d    1833 non-null   float64
 13  gravidade_lag_7d   1833 non-null   float64
 14  casos_mm7d         1833 non-null   float64
 15  chuva_acum_15d     1833 non-null   float64
 16  temp_max_lag_15d   1833 non-null   float64
 17  temp_min_lag_15d   1833 non-null   float64
 18  gravidade_lag_15d  1833 non-null   float64
 19  casos_mm15d        1833 non-null   float64
 20  chuva_acum_21d     1833 non-null   float64
 21  temp_max_lag_21d   1833 non-null   float64
 22  temp_min_lag_21d   1833 non-null   float64
 23  gravidade_lag_21d  1833 non-null   float64
 24  casos_mm21d        1833 non-null   float64
 25  chuva_acum_30d     1833 non-null   float64
 26  temp_max_lag_30d   1833 non-null   float64
 27  temp_min_lag_30d   1833 non-null   float64
 28  gravidade_lag_30d  1833 non-null   float64
 29  casos_mm30d        1833 non-null   float64
 30  chuva_acum_45d     1833 non-null   float64
 31  temp_max_lag_45d   1833 non-null   float64
 32  temp_min_lag_45d   1833 non-null   float64
 33  gravidade_lag_45d  1833 non-null   float64
 34  casos_mm45d        1833 non-null   float64
 35  chuva_acum_50d     1833 non-null   float64
 36  temp_max_lag_50d   1833 non-null   float64
 37  temp_min_lag_50d   1833 non-null   float64
 38  gravidade_lag_50d  1833 non-null   float64
 39  casos_mm50d        1833 non-null   float64
 40  chuva_acum_60d     1833 non-null   float64
 41  temp_max_lag_60d   1833 non-null   float64
 42  temp_min_lag_60d   1833 non-null   float64
 43  gravidade_lag_60d  1833 non-null   float64
 44  casos_mm60d        1833 non-null   float64
 45  day_month          1833 non-null   int32
 46  day_month_start    1833 non-null   int64
 47  day_month_end      1833 non-null   int64
 48  day_quarter_start  1833 non-null   int64
 49  day_quarter_end    1833 non-null   int64
 50  day_year_start     1833 non-null   int64
 51  day_year_end       1833 non-null   int64
 52  faixa_umidade      1833 non-null   category
dtypes: category(2), float64(41), int32(4), int64(6)
memory usage: 720.0 KB

In [317]:
def encode_categorical_columns(df):
    df_encoded = df.copy()
    cat_cols = df_encoded.select_dtypes(include=['category', 'object']).columns

    for col in cat_cols:
        print(f"Transformando a coluna: {col}")
        df_encoded[col] = df_encoded[col].cat.codes

    return df_encoded

In [318]:
X_train_s = encode_categorical_columns(X_train_s)
X_val_s = encode_categorical_columns(X_val_s)
X_test_s = encode_categorical_columns(X_test_s)

Transformando a coluna: faixa_chuva
Transformando a coluna: faixa_umidade
Transformando a coluna: faixa_chuva
Transformando a coluna: faixa_umidade
Transformando a coluna: faixa_chuva
Transformando a coluna: faixa_umidade

In [320]:
scaler = StandardScaler()

In [321]:
X_train_scaled = scaler.fit_transform(X_train_s)
X_val_scaled = scaler.transform(X_val_s)
X_test_scaled = scaler.transform(X_test_s)

In [331]:
X_train_scaled_df = pd.DataFrame(X_train_scaled,
                                 columns=X_train_s.columns,
                                 index=X_train_s.index)

X_val_scaled_df = pd.DataFrame(X_val_scaled,
                                 columns=X_val_s.columns,
                                 index=X_val_s.index)

X_test_scaled_df = pd.DataFrame(X_test_scaled,
                                 columns=X_test_s.columns,
                                 index=X_test_s.index)

X_train_scaled_df

,score_gravidade,idade,chuva_dia,temp_max_dia,temp_min_dia,umidade_dia,year,month,day_week,chuva_acum_7d,...,gravidade_lag_60d,casos_mm60d,day_month,day_month_start,day_month_end,day_quarter_start,day_quarter_end,day_year_start,day_year_end,faixa_umidade
data,,,,,,,,,,,,,,,,,,,,,
2020-03-01,0.869640,-0.446933,14.949865,-1.420727,0.896071,1.918765,-1.592496,-1.030817,1.496151,4.871888,...,0.711506,-0.367691,-1.674526,5.344578,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899
2020-03-02,0.139131,0.094649,1.376479,-1.444362,0.348351,1.715908,-1.592496,-1.030817,-1.482069,5.399808,...,-0.932760,-0.368604,-1.560000,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899
2020-03-03,0.827495,0.081831,0.030893,-0.546237,0.445008,0.929490,-1.592496,-1.030817,-0.985699,5.467631,...,0.198373,-0.369516,-1.445474,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899
2020-03-04,-0.116547,-1.146823,-0.257028,-0.688046,0.799415,0.616868,-1.592496,-1.030817,-0.489329,5.462132,...,1.407901,-0.369516,-1.330949,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899
2020-03-05,0.371566,0.155246,-0.227648,-0.309888,-0.296024,0.183365,-1.592496,-1.030817,0.007041,5.005701,...,0.556752,-0.369212,-1.216423,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,-0.753487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-22,0.991391,-0.743182,-0.345166,0.588237,-0.811525,-0.152878,1.570067,0.491245,0.503411,-0.733594,...,-0.003215,-0.339548,0.730516,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,-0.753487
2025-08-23,-1.139259,0.563325,-0.345166,1.108204,-1.069276,-2.801135,1.570067,0.491245,0.999781,-0.755591,...,-0.607979,-0.340612,0.845042,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,-2.642872
2025-08-24,-0.286999,-0.585800,-0.345166,-0.309888,-0.618212,-0.539140,1.570067,0.491245,1.496151,-0.755591,...,-0.507185,-0.341373,0.959568,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,-0.753487
2025-08-25,-0.774005,-0.616549,-0.345166,-0.286253,0.541664,0.962836,1.570067,0.491245,-1.482069,-0.755591,...,-0.379512,-0.342590,1.074093,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899
2025-08-26,0.458729,-0.009501,-0.239400,-1.066204,0.380570,1.745086,1.570067,0.491245,-0.985699,-0.722596,...,-1.145547,-0.344720,1.188619,-0.187106,-0.182368,-0.107654,-0.099586,-0.046765,-0.03305,1.135899

In [332]:
X_train_scaled = pd.concat([X_train_scaled_df, X_train_fourier], axis=1)
X_val_scaled = pd.concat([X_val_scaled_df, X_val_fourier], axis=1)
X_test_scaled = pd.concat([X_test_scaled_df, X_test_fourier], axis=1)

In [333]:
X_train_scaled.shape, X_train.shape

((1833, 65), (1833, 65))

In [334]:
X_val_scaled.shape, X_val.shape

((60, 65), (60, 65))

In [335]:
X_test_scaled.shape, X_test.shape

((60, 65), (60, 65))

In [337]:
X_test_scaled.head()

,score_gravidade,idade,chuva_dia,temp_max_dia,temp_min_dia,umidade_dia,year,month,day_week,chuva_acum_7d,...,ciclos_fourier_cos_p7_k2,ciclos_fourier_sin_p7_k2,ciclos_fourier_cos_p7_k3,ciclos_fourier_sin_p7_k3,ciclos_fourier_cos_p30_k1,ciclos_fourier_sin_p30_k1,ciclos_fourier_cos_p365_k1,ciclos_fourier_sin_p365_k1,ciclos_fourier_cos_p365_k2,ciclos_fourier_sin_p365_k2
data,,,,,,,,,,,,,,,,,,,,,
2025-10-26,-0.020668,0.037366,-0.345166,1.628171,-0.231587,-1.986928,1.570067,1.100069,1.496151,-0.652940,...,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
2025-10-27,0.139131,-0.699671,-0.274655,0.162809,-0.360462,0.734969,1.570067,1.100069,-1.482069,-0.733594,...,-0.222521,0.974928,-0.900969,0.433884,0.978148,0.207912,0.999852,0.017213,0.999407,0.034422
2025-10-28,-0.500064,0.240459,0.007389,-0.238984,0.316133,1.475536,1.570067,1.100069,-0.985699,-0.623611,...,-0.900969,-0.433884,0.623490,-0.781831,0.913545,0.406737,0.999407,0.034422,0.997630,0.068802
2025-10-29,-0.500064,-0.462555,-0.339291,0.493697,0.122820,0.689813,1.570067,1.100069,-0.489329,-0.621778,...,0.623490,-0.781831,-0.222521,0.974928,0.809017,0.587785,0.998667,0.051620,0.994671,0.103102
2025-10-30,0.139131,-0.419159,0.365820,-1.184378,0.090601,1.037865,1.570067,1.100069,0.007041,-0.399978,...,0.623490,0.781831,-0.222521,-0.974928,0.669131,0.743145,0.997630,0.068802,0.990532,0.137279

In [338]:
print_nan(X_train_scaled)
print_nan(X_val_scaled)
print_nan(X_test_scaled)

Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!
Nenhum valor NaN encontrado!

# Feature Selection

In [ ]:
def feature_selection(X_train, y_train, X_test, model, scoring='neg_root_mean_squared_error', cv=3, threshold=0.001):
    """
    Executa feature selection usando RecursiveFeatureElimination com o modelo cru.
    """
    estimator = clone(model)

    feat_selector = RecursiveFeatureElimination(
        variables=None,
        estimator=estimator,
        scoring=scoring,
        threshold=threshold,
        cv=cv,
    )

    feat_selector.fit(X_train.copy(), y_train)
    X_train_fs = feat_selector.transform(X_train.copy())
    X_test_fs = feat_selector.transform(X_test.copy())

    return X_train_fs, X_test_fs, feat_selector

# Hyperparam Optimization

In [ ]:
def optimize_model(X_train, y_train, model_name='XGBoost', n_trials=50, n_splits=10, random_state=42):
    """
    Realiza hyperparameter optimization usando Optuna para modelos clássicos de regressão.
    Retorna o melhor dicionário de parâmetros (best_params).
    """

    tscv = TimeSeriesSplit(n_splits=n_splits)

    # Função objetivo para Optuna
    def objective(trial):
        if model_name == 'XGBoost':
            parans = {
                "device": "cuda",
                "tree_method": "hist",
                "n_estimators": trial.suggest_int('n_estimators', 100, 500),
                "max_depth": trial.suggest_int('max_depth', 3, 8),
                "learning_rate": trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
                "subsample": trial.suggest_float('subsample', 0.6, 0.9),
                "colsample_bytree": trial.suggest_float('colsample_bytree', 0.5, 1.0),
                "n_jobs": -1,
                "random_state": random_state
            }
            n_estimators = trial.suggest_int('n_estimators', 100, 500)
            max_depth = trial.suggest_int('max_depth', 3, 8)
            learning_rate = trial.suggest_float('learning_rate', 0.01, 0.1, log=True)
            subsample = trial.suggest_float('subsample', 0.6, 0.9)
            colsample_bytree = trial.suggest_float('colsample_bytree', 0.5, 1.0)
            model = XGBRegressor(**params)

        elif model_name == 'LightGBM':
            parans = {
                "device": "gpu",
                "gpu_platform_id": 0,
                "gpu_device_id": 0,
                "n_estimators": trial.suggest_int('n_estimators', 100, 500),
                "max_depth": trial.suggest_int('max_depth', 3, 8),
                "learning_rate": trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
                "num_leaves": trial.suggest_int('num_leaves', 20, 60),
                "subsample": trial.suggest_float('subsample', 0.5, 1.0),
                "colsample_bytree": trial.suggest_float('colsample_bytree', 0.5, 1.0),
                "n_jobs": -1,
                "random_state": random_state
            }
            model = LGBMRegressor(**params)
        else:
            raise ValueError(f'Model {model_name} não suportado.')

        # Avaliação com TimeSeriesSplit
        scores = cross_val_score(
            model, X_train, y_train,
            cv=tscv,
            scoring=make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred))),
            n_jobs=-1
        )

        return np.mean(scores)  # Optuna minimiza RMSE médio

    # Criar estudo e otimizar
    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials)

    # print(f"Melhores parâmetros para {model_name}: {study.best_params}")
    # print(f"Melhor RMSE médio (CV): {study.best_value:.4f}")

    # Retorna os melhores parâmetros (para Linear será vazio)
    return study.best_params

# Forecasting

In [339]:
def forecasting(X_train, y_train, X_val, model_name, n_trials=10, n_splits=15):
  """
  Executa o fluxo completo:
  - Otimiza hiperparâmetros com Optuna
  - Seleciona features com modelo cru
  - Treina e prevê com modelo otimizado
  """
  X_train_ = X_train.copy()
  X_val_ = X_val.copy()
  y_train_ = y_train.copy()

  # ----  Hyperparameter tuning ----
  best_params = optimize_model(X_train_, y_train_, model_name=model_name, n_trials=n_trials, n_splits=n_splits)
  if best_params is None:
      best_params = {}

  # ---- Criação do modelo otimizado ----
  model_map = {
      'XGBoost': XGBRegressor,
      'LightGBM': LGBMRegressor
  }

  if model_name not in model_map:
      raise ValueError(f"Modelo {model_name} não suportado.")

  # modelo otimizado (para previsão final)
  model_opt = model_map[model_name](**best_params)

  # modelo cru (para seleção de features)
  model_raw = model_map[model_name]()

  # ---- Feature selection com modelo cru ----
  X_train_fs, X_val_fs, feat_selected = feature_selection(
      X_train_, y_train_, X_val_, model_raw, scoring='neg_root_mean_squared_error', cv=5, threshold=0.001
  )

  # ---- Treinamento e previsão ----
  model_opt.fit(X_train_fs, y_train_)
  y_pred = model_opt.predict(X_val_fs)

  return y_pred, best_params, feat_selected, model_opt

# Metrics/Results

In [340]:
df_result = pd.DataFrame()
forecast_metric = dict()

In [341]:
def get_erros_metric(x_test, pedrict, forecast_metric, time):
  mse = mean_squared_error(x_test,pedrict)
  forecast_metric.update({'MSE':mse})

  RMSE = np.sqrt(mse)
  forecast_metric.update({'RMSE':RMSE})

  r2 = r2_score(y_test, y_pred_final)
  forecast_metric.update({'R2':r2})

  forecast_metric.update({'Seconds':round(time,6)})

  return forecast_metric

In [342]:
def add_resultado(df_result: pd.DataFrame, forecast_method: str, method: dict) -> pd.DataFrame:
    # Se ainda não tem coluna 'Type', cria
    if "Type" not in df_result.columns:
        df_result["Type"] = None

    # Verifica se já existe linha para esse método
    mask = df_result["Type"] == forecast_method

    if mask.any():
        # Atualiza as métricas na linha existente
        for key, value in method.items():
            df_result.loc[mask, key] = value
    else:
        # Cria nova linha com Type e métricas
        new_row = {"Type": forecast_method}
        new_row.update(method)
        df_result = pd.concat([df_result, pd.DataFrame([new_row])], ignore_index=True)

    forecast_metric.clear()
    return df_result

# XGBoost

In [343]:
start_time = time.time()
model_name = 'XGBoost'
y_pred_xg_boost, best_params_xg_boost, feat_selected_xg_boost, model_xg_boost = forecasting(X_train_scaled, y_train, X_val_scaled, model_name, 50)
end_time = time.time()

[I 2026-05-10 22:59:33,222] A new study created in memory with name: no-name-2ec33871-04af-49a5-8d58-09c107b227bf
[I 2026-05-10 23:00:35,804] Trial 0 finished with value: 44.84136189261969 and parameters: {'n_estimators': 275, 'max_depth': 7, 'learning_rate': 0.032456534346239116, 'subsample': 0.8230295717519495, 'colsample_bytree': 0.7987770605035214}. Best is trial 0 with value: 44.84136189261969.
[I 2026-05-10 23:00:49,750] Trial 1 finished with value: 44.239392957079716 and parameters: {'n_estimators': 278, 'max_depth': 5, 'learning_rate': 0.036493651445566266, 'subsample': 0.8105828176069343, 'colsample_bytree': 0.5049652023317979}. Best is trial 1 with value: 44.239392957079716.
[I 2026-05-10 23:01:11,956] Trial 2 finished with value: 44.20352399265164 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.010273345875376101, 'subsample': 0.6582304468841544, 'colsample_bytree': 0.7340266669471758}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:02:08,273] Trial 3 finished with value: 44.59840026449094 and parameters: {'n_estimators': 265, 'max_depth': 8, 'learning_rate': 0.05390191794132909, 'subsample': 0.7409937565770687, 'colsample_bytree': 0.849632070376572}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:03:17,819] Trial 4 finished with value: 44.84648883321954 and parameters: {'n_estimators': 307, 'max_depth': 8, 'learning_rate': 0.055665369125456575, 'subsample': 0.844961034333802, 'colsample_bytree': 0.879726424470683}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:04:49,944] Trial 5 finished with value: 45.02490030837136 and parameters: {'n_estimators': 416, 'max_depth': 8, 'learning_rate': 0.05693633681106888, 'subsample': 0.7789082635074682, 'colsample_bytree': 0.8225093296506393}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:05:49,118] Trial 6 finished with value: 44.60724532919123 and parameters: {'n_estimators': 316, 'max_depth': 8, 'learning_rate': 0.023784893586824816, 'subsample': 0.6478819527875529, 'colsample_bytree': 0.803456534945209}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:05:57,421] Trial 7 finished with value: 44.9747445511129 and parameters: {'n_estimators': 113, 'max_depth': 4, 'learning_rate': 0.023364946479924403, 'subsample': 0.8587080991197421, 'colsample_bytree': 0.6809472162645493}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:06:23,642] Trial 8 finished with value: 45.075776925410814 and parameters: {'n_estimators': 395, 'max_depth': 4, 'learning_rate': 0.06401340963813142, 'subsample': 0.7885794657760965, 'colsample_bytree': 0.9502059188479031}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:08:20,937] Trial 9 finished with value: 44.61076802313614 and parameters: {'n_estimators': 472, 'max_depth': 8, 'learning_rate': 0.01607858674747955, 'subsample': 0.7100905487393393, 'colsample_bytree': 0.9327118184919239}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:08:26,438] Trial 10 finished with value: 45.00009084788384 and parameters: {'n_estimators': 166, 'max_depth': 3, 'learning_rate': 0.010837000035784037, 'subsample': 0.6027429923864858, 'colsample_bytree': 0.6570554456243742}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:08:51,829] Trial 11 finished with value: 44.4223771939278 and parameters: {'n_estimators': 365, 'max_depth': 6, 'learning_rate': 0.0355053758876206, 'subsample': 0.8978337621561601, 'colsample_bytree': 0.503122699967729}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:09:05,887] Trial 12 finished with value: 44.57925286564979 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.01315902477071076, 'subsample': 0.6868174070303052, 'colsample_bytree': 0.5185019817454178}. Best is trial 2 with value: 44.20352399265164.
[I 2026-05-10 23:09:32,738] Trial 13 finished with value: 44.13335746633847 and parameters: {'n_estimators': 462, 'max_depth': 5, 'learning_rate': 0.0969373275612994, 'subsample': 0.6501206724907924, 'colsample_bytree': 0.5932056595722401}. Best is trial 13 with value: 44.13335746633847.
[I 2026-05-10 23:10:22,614] Trial 14 finished with value: 43.906160227958004 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.09866656797503912, 'subsample': 0.6364059425390602, 'colsample_bytree': 0.6113945872538082}. Best is trial 14 with value: 43.906160227958004.
[I 2026-05-10 23:11:05,589] Trial 15 finished with value: 44.05005620292878 and parameters: {'n_estimators': 499, 'max_depth': 6, 'learning_rate': 0.09733457034613727, 'subsample': 0.6165139779051432, 'colsample_bytree': 0.5979996812862072}. Best is trial 14 with value: 43.906160227958004.
[I 2026-05-10 23:11:44,851] Trial 16 finished with value: 43.84124372667061 and parameters: {'n_estimators': 471, 'max_depth': 6, 'learning_rate': 0.08425036379758014, 'subsample': 0.6080912420165682, 'colsample_bytree': 0.6027934729653991}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:12:40,634] Trial 17 finished with value: 45.42725524446096 and parameters: {'n_estimators': 430, 'max_depth': 7, 'learning_rate': 0.07403579273411949, 'subsample': 0.7064677360468427, 'colsample_bytree': 0.6006011058433453}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:13:43,316] Trial 18 finished with value: 44.7361891554334 and parameters: {'n_estimators': 450, 'max_depth': 7, 'learning_rate': 0.07871490077669845, 'subsample': 0.6310005308723192, 'colsample_bytree': 0.7112550315561069}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:14:27,810] Trial 19 finished with value: 45.62291191996499 and parameters: {'n_estimators': 497, 'max_depth': 6, 'learning_rate': 0.07902916896443384, 'subsample': 0.6806137195319799, 'colsample_bytree': 0.6351435161873337}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:15:05,260] Trial 20 finished with value: 45.05343593408661 and parameters: {'n_estimators': 370, 'max_depth': 6, 'learning_rate': 0.04160896050885843, 'subsample': 0.7428294959450813, 'colsample_bytree': 0.7583217596621173}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:15:43,769] Trial 21 finished with value: 44.00406950497072 and parameters: {'n_estimators': 494, 'max_depth': 6, 'learning_rate': 0.096028055464063, 'subsample': 0.601937282255403, 'colsample_bytree': 0.5687349064026876}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:16:38,711] Trial 22 finished with value: 44.909152112639255 and parameters: {'n_estimators': 473, 'max_depth': 7, 'learning_rate': 0.0953683373825485, 'subsample': 0.6017614059809058, 'colsample_bytree': 0.5590172262690796}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:17:12,871] Trial 23 finished with value: 43.91674182258488 and parameters: {'n_estimators': 436, 'max_depth': 6, 'learning_rate': 0.04515494727467899, 'subsample': 0.6300805638579825, 'colsample_bytree': 0.5582180983897046}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:17:28,023] Trial 24 finished with value: 43.92220282997766 and parameters: {'n_estimators': 422, 'max_depth': 4, 'learning_rate': 0.048848191126589, 'subsample': 0.6319208507630475, 'colsample_bytree': 0.6366441704975498}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:18:07,790] Trial 25 finished with value: 44.35649747219631 and parameters: {'n_estimators': 349, 'max_depth': 7, 'learning_rate': 0.06783199002213186, 'subsample': 0.6789978551770793, 'colsample_bytree': 0.5488425661925056}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:18:47,122] Trial 26 finished with value: 44.099720115454794 and parameters: {'n_estimators': 443, 'max_depth': 6, 'learning_rate': 0.025146181948104272, 'subsample': 0.6601698195765883, 'colsample_bytree': 0.6888086502080246}. Best is trial 16 with value: 43.84124372667061.
[I 2026-05-10 23:19:13,593] Trial 27 finished with value: 43.65948992520728 and parameters: {'n_estimators': 402, 'max_depth': 5, 'learning_rate': 0.04330762559870359, 'subsample': 0.6297622128291447, 'colsample_bytree': 0.6297953006519466}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:19:49,063] Trial 28 finished with value: 44.3369805143676 and parameters: {'n_estimators': 402, 'max_depth': 5, 'learning_rate': 0.019596348565499532, 'subsample': 0.7022075045977363, 'colsample_bytree': 0.6332391297811177}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:19:55,980] Trial 29 finished with value: 44.03711625887056 and parameters: {'n_estimators': 333, 'max_depth': 3, 'learning_rate': 0.027770568160596892, 'subsample': 0.6259094505940742, 'colsample_bytree': 0.7621941600731962}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:20:06,204] Trial 30 finished with value: 44.91844452879546 and parameters: {'n_estimators': 235, 'max_depth': 4, 'learning_rate': 0.08041533208067929, 'subsample': 0.7248911458212837, 'colsample_bytree': 0.6704622886957936}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:20:40,924] Trial 31 finished with value: 44.11519669743421 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.041948842980030314, 'subsample': 0.6435050556071632, 'colsample_bytree': 0.5482403429191092}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:21:08,326] Trial 32 finished with value: 44.21176952995304 and parameters: {'n_estimators': 474, 'max_depth': 5, 'learning_rate': 0.04469049701285924, 'subsample': 0.6716833249148035, 'colsample_bytree': 0.6119467721512992}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:21:48,443] Trial 33 finished with value: 44.57144822172026 and parameters: {'n_estimators': 408, 'max_depth': 7, 'learning_rate': 0.03550776523348817, 'subsample': 0.6160505843484783, 'colsample_bytree': 0.5276006386530332}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:22:12,203] Trial 34 finished with value: 44.27241092337487 and parameters: {'n_estimators': 432, 'max_depth': 5, 'learning_rate': 0.029582567367625552, 'subsample': 0.6370513881021632, 'colsample_bytree': 0.581925245301602}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:23:00,254] Trial 35 finished with value: 44.67160295847629 and parameters: {'n_estimators': 480, 'max_depth': 6, 'learning_rate': 0.06366358370780283, 'subsample': 0.6658971056302913, 'colsample_bytree': 0.7078800190682613}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:23:24,850] Trial 36 finished with value: 44.288521727607616 and parameters: {'n_estimators': 453, 'max_depth': 5, 'learning_rate': 0.0546700962010685, 'subsample': 0.619379190405901, 'colsample_bytree': 0.6219816790574039}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:23:47,360] Trial 37 finished with value: 44.92645736234147 and parameters: {'n_estimators': 275, 'max_depth': 6, 'learning_rate': 0.050391036007211454, 'subsample': 0.7582096348140831, 'colsample_bytree': 0.5358851248939499}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:25:02,828] Trial 38 finished with value: 44.55954096683105 and parameters: {'n_estimators': 395, 'max_depth': 7, 'learning_rate': 0.0853042042182292, 'subsample': 0.6541439709581804, 'colsample_bytree': 0.6544470326145688}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:25:35,263] Trial 39 finished with value: 44.49290010034652 and parameters: {'n_estimators': 382, 'max_depth': 5, 'learning_rate': 0.07108685003616268, 'subsample': 0.6947349485433042, 'colsample_bytree': 0.9913891121324049}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:25:45,160] Trial 40 finished with value: 45.24207443678678 and parameters: {'n_estimators': 297, 'max_depth': 4, 'learning_rate': 0.03971219208203297, 'subsample': 0.822344080955956, 'colsample_bytree': 0.7287519862069336}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:26:00,265] Trial 41 finished with value: 43.97586741362875 and parameters: {'n_estimators': 422, 'max_depth': 4, 'learning_rate': 0.05045004782880377, 'subsample': 0.6375310911694402, 'colsample_bytree': 0.6432243457881746}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:26:09,962] Trial 42 finished with value: 44.00678389814277 and parameters: {'n_estimators': 430, 'max_depth': 3, 'learning_rate': 0.06135260048202694, 'subsample': 0.615816267622362, 'colsample_bytree': 0.5746210468738479}. Best is trial 27 with value: 43.65948992520728.
[I 2026-05-10 23:26:28,958] Trial 43 finished with value: 43.62629580083004 and parameters: {'n_estimators': 412, 'max_depth': 4, 'learning_rate': 0.04714298337921928, 'subsample': 0.6290538854334266, 'colsample_bytree': 0.6164957167653086}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:26:56,623] Trial 44 finished with value: 44.03374134678188 and parameters: {'n_estimators': 483, 'max_depth': 5, 'learning_rate': 0.031028942934336532, 'subsample': 0.6594113156360312, 'colsample_bytree': 0.6149463194093499}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:27:27,378] Trial 45 finished with value: 44.38072209722102 and parameters: {'n_estimators': 358, 'max_depth': 6, 'learning_rate': 0.03381757898219235, 'subsample': 0.6459758502097868, 'colsample_bytree': 0.6678949135298257}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:27:53,149] Trial 46 finished with value: 43.863966576290885 and parameters: {'n_estimators': 381, 'max_depth': 5, 'learning_rate': 0.046637685616672614, 'subsample': 0.6090792837401217, 'colsample_bytree': 0.8572631115533266}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:28:09,460] Trial 47 finished with value: 43.75888051884228 and parameters: {'n_estimators': 379, 'max_depth': 4, 'learning_rate': 0.058904741078035734, 'subsample': 0.600114441742369, 'colsample_bytree': 0.8347868697185618}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:28:25,257] Trial 48 finished with value: 43.93371839994315 and parameters: {'n_estimators': 339, 'max_depth': 4, 'learning_rate': 0.0578506113991919, 'subsample': 0.6113152070827086, 'colsample_bytree': 0.865032421371428}. Best is trial 43 with value: 43.62629580083004.
[I 2026-05-10 23:28:34,786] Trial 49 finished with value: 43.69520702529596 and parameters: {'n_estimators': 381, 'max_depth': 3, 'learning_rate': 0.03812440283841717, 'subsample': 0.6001007529442509, 'colsample_bytree': 0.8219684015248756}. Best is trial 43 with value: 43.62629580083004.

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [344]:
print(f'{model_name}: {best_params_xg_boost}')

NameError: name 'best_params_xg_boost' is not defined

In [345]:
feat_selected_xg_boost.initial_model_performance_

NameError: name 'feat_selected_xg_boost' is not defined

In [ ]:
len(feat_selected_xg_boost.features_to_drop_)

In [ ]:
feat_selected_xg_boost.feature_importances_.plot.bar(figsize=(20,6))
plt.xlabel('Features')
plt.ylabel('Importance')
plt.title(label=f'{model_name}')
plt.show()

In [ ]:
pd.Series(feat_selected_xg_boost.performance_drifts_).plot.bar(figsize=(20,6))
plt.xlabel('Features')
plt.ylabel('Performance change when feature was added')
plt.title(label=f'{model_name}')
plt.show()

In [ ]:
# metrics = get_erros_metric(y_val, y_pred_xg_boost, forecast_metric, (end_time - start_time))
# df_result = add_resultado(df_result, model_name, metrics)
# df_result

In [ ]:
plt.figure(figsize=(12,5))
plt.plot(y_val.index, y_val, label='Real',  color='green', lw=2)
plt.plot(y_val.index, y_pred_xg_boost, label='Previsto', color='orange', lw=2)
plt.title(f"{model_name} - Previsão vs Real (Validação)")
plt.xlabel("Date")
plt.ylabel("Close")
plt.legend()
plt.show()

In [ ]:
y_pred_final = model_xg_boost.predict(X_test_scaled)

In [ ]:
plt.figure(figsize=(12,5))
plt.plot(y_test.index, y_test, label='Real',  color='green', lw=2)
plt.plot(y_test.index, y_pred_final, label='Previsto', color='orange', lw=2)
plt.title(f"{model_name} - Previsão vs Real (Test)")
plt.xlabel("Date")
plt.ylabel("Close")
plt.legend()
plt.show()

In [ ]:
# Em séries temporais, como o seu projeto de dengue/saúde, após você validar tudo
# e chegar à conclusão de que o modelo é bom usando o `X_val`, existe um passo extra muito comum:

# **Retreinar o modelo com Treino + Validação:**
# Antes de fazer a predição final no Teste, muitos cientistas de dados juntam o Treino e
# a Validação em um único bloco e treinam o modelo uma última vez com esses dados combinados.
# Porque assim o modelo terá visto os dados mais recentes (da validação)
# antes de tentar prever o teste, o que é valioso para capturar as tendências mais próximas de 2026.

# Opcional: Juntar treino e val para o último treino antes do teste real
X_final_train = pd.concat([X_train_scaled, X_val_scaled])
y_final_train = pd.concat([y_train, y_val])

# modelo.fit(X_final_train, y_final_train)
y_pred_final_2 = model_xg_boost.predict(X_test_scaled) # Comparar com y_test

In [ ]:
plt.figure(figsize=(12,5))
plt.plot(y_test.index, y_test, label='Real',  color='green', lw=2)
plt.plot(y_test.index, y_pred_final_2, label='Previsto', color='orange', lw=2)
plt.title(f"{model_name} - Previsão vs Real (Test 2)")
plt.xlabel("Date")
plt.ylabel("Close")
plt.legend()
plt.show()